# Generated by Django 5.2.7 on 2025-10-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='allergies', to='main_app.food'),
        ),
    ]
