# Generated by Django 5.2.7 on 2025-10-11 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_allergy_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
