# Generated by Django 5.2.7 on 2025-10-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='generation_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
