# Generated by Django 5.2.7 on 2025-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
